name: haskell-callgraph

dependencies:
  - attoparsec
  - base
  - bytestring
  - conduit
  - containers
  - extra
  - kythe-importer
  - kythe-proto
  - kythe-schema
  - lens-family
  - mtl
  - regex-compat
  - text
  - rio
  - store
  - vector

library:
  source-dirs: src
  ghc-options: [-Wall]
  exposed-modules:
    - CallGraph
    - Data.Graph.Sparse
    - Language.Haskell.Source
    - Language.Haskell.Source.IO

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - hspec
      - haskell-callgraph
    build-tools: hspec-discover

executables:
  kythe-to-call-graph:
    source-dirs: kythe-to-call-graph
    main: Main
    dependencies:
      - haskell-callgraph
      - kythe-importer
      - optparse-applicative
  query-tool:
    source-dirs: query-tool
    main: Main.hs
    dependencies:
      - haskell-callgraph
      - optparse-applicative
  navigator:
    source-dirs: navigator
    dependencies:
      - brick
      - haskell-callgraph
      - kythe-importer
      - microlens
      - optparse-applicative
      - vector
      - vty
    main: Main.hs
    ghc-options: [-threaded]
