name: haskell-callgraph

dependencies:
  - attoparsec
  - base
  - bytestring
  - conduit
  - containers
  - extra
  - kythe-proto
  - kythe-schema
  - lens-family
  - mtl
  - regex-compat
  - text
  - rio
  - vector

library:
  source-dirs: src
  exposed-modules:
    - CallGraph

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - hspec
      - haskell-callgraph
    build-tools: hspec-discover

executables:
  query-tool:
    source-dirs: query-tool
    main: Main.hs
    dependencies:
      - haskell-callgraph
      - kythe-importer
      - optparse-applicative
  navigator:
    source-dirs: navigator
    dependencies:
      - brick
      - haskell-callgraph
      - kythe-importer
      - microlens
      - optparse-applicative
      - vector
      - vty
    main: Main.hs
    ghc-options: [-threaded]
