name: haskell-callgraph

dependencies:
  - attoparsec
  - base
  - bytestring
  - conduit
  - containers
  - kythe-proto
  - lens-family
  - text

library:
  source-dirs: src
  exposed-modules:
    - CallGraph

executables:
  query-tool:
    source-dirs: query-tool
    main: Main.hs
    dependencies:
      - haskell-callgraph
      - kythe-importer
  navigator:
    source-dirs: navigator
    dependencies:
#      - attoparsec
#      - base
      - brick
#      - bytestring
#      - conduit
#      - conduit-extra
#      - containers
#      - kythe-proto
#      - lens-family
      - haskell-callgraph
      - kythe-importer
      - microlens
#      - proto-lens
#      - text
      - optparse-applicative
      - vector
      - vty
    main: Main.hs
    ghc-options: [-threaded]
