name: test-lib
version: 0.1.0

dependencies:
  - base >= 4.7

library:
  source-dirs: src
  exposed-modules:
    - A
    - B
    - ClassA

executables:
  exe1:
    source-dirs: exe1
    main: Main.hs
  exe2:
    source-dirs: exe2
    dependencies: [test-lib]
    main: Main.hs
